### ISSUE TITLE
Issue With Raditz Loader

### ISSUE THREAD

**Issue by Arszilla** [jfmaes/CSharpReflectionWorkshop#1]
Hi there,

I was following your GitBook for reflective loading with C# and encountered a strange issue with in Section 2, with Raditz Loader.

For some strange reason, I'm getting the following error on both `.NET 3.1` (LTS) and `.NET 5.0`:
```
System.BadImageFormatException: 'Bad IL format. The format of the file 'C:\Users\<username>\source\repos\Reflection World\Reflection World\bin\Release\net5.0\Reflection World.exe' is invalid.'
```

My code Raditz code is identical to yours:

```csharp
using System;
using System.Reflection;


namespace Raditz
{
    class Program
    {
        static void Reflect(string FilePath)
        {
            Assembly dotNetProgram = Assembly.LoadFile(FilePath);
            Object[] parameters = new String[] { null };
            dotNetProgram.EntryPoint.Invoke(null, parameters);
        }

        static void Main(string[] args)
        {
            Reflect(@"C:\Users\<username>\source\repos\Reflection World\Reflection World\bin\Release\net5.0\Reflection World.exe");
        }
    }
}
```

while my `Reflection World` is the same from Section 1:

```csharp
using System;
using System.Reflection;

namespace Reflection_World
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello from Reflection World!");
            Console.ReadKey();
        }
    }
}
```

At first, I thought it had to do with the `.NET` versions, because some threads in SO made me think so, but trying to execute `Raditz Loader.exe` would just give the same error (despite both projects being re-made in `.NET 3.1`). I also thought that `Any CPU` might've been the cause, but that changed nothing despite trying both `x86` then a `x64` CPU.

Any idea on what the cause for this might be?

**Comment by jfmaes** [comment]
Are you using dotnet FRAMEWORK? Not core?

**Comment by Arszilla** [comment]
Ah damn. I must've chosen the wrong project during Raditz's creation. I can't believe I've overlooked it for the past few hours. Thank you for pointing it out.

I apologize for the silly mistake. I'll close the issue as it's now resolved.

Thanks once again!
